### ISSUE TITLE
Nav items overlapping Pomodoro clock elements in mobile screen

### ISSUE THREAD

**Issue by rohitbabugaddeti** [Kira272921/Its-Time-To-Focus#1]
When the app is opened in mobile screen, navigated into `/pomodoro/25-5/pomodoro.html` and clicked on `hamburger icon > Pomodoro clock`, the nav dropdown overlaps with types of timers on the page.

**Suggested fix:** On the other pages of the app, the nav dropdown when opened, is pushing down other elements below it. But it's not happening with `/pomodoro/25-5/pomodoro.html`. Applying a similar behavior on this page could solve the issue

**Comment by rohitbabugaddeti** [comment]
Screenshot of the issue 👇

![image](https://user-images.githubusercontent.com/30732419/149616057-33333453-da18-4803-a228-d6932be843ae.png)

**Comment by 0xMukesh** [comment]
@rohitbabugaddeti Thanks for reporting the issue 😄. I'll try to fix the issue by today or tomorrow afternoon 👀. If you are interested to resolve the issue let me know, I will assign you

**Comment by rohitbabugaddeti** [comment]
Lemme try :)

Will let you know if it doesn't work. You can go ahead and apply the fix
